FROM php:7.0.33-fpm-jessie

LABEL maintainer "zhouyueqiu zhouyueqiu@easycorp.ltd"

ENV OS_ARCH="amd64" \
    OS_NAME="debian9" \
    HOME_PAGE="https://modstart.com/"

COPY debian/prebuildfs /

ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list \
    && curl -k -o /tmp/freexian-archive-keyring_2022.06.08_all.deb https://deb.freexian.com/extended-lts/pool/main/f/freexian-archive-keyring/freexian-archive-keyring_2022.06.08_all.deb \
    && dpkg -i /tmp/freexian-archive-keyring_2022.06.08_all.deb \
    && curl -k -o /tmp/elts-archive-key.gpg https://deb.freexian.com/extended-lts/archive-key.gpg \
    && mv /tmp/elts-archive-key.gpg /etc/apt/trusted.gpg.d/freexian-archive-extended-lts.gpg

RUN apt-get update ; \
    apt-get install -y --force-yes --no-install-recommends curl wget zip unzip pwgen cron netcat nginx rsync

# Install s6
RUN . /opt/easysoft/scripts/libcomponent.sh && component_unpack "s6" "2.11.1.3" \
    -c e713c386993f7891b039256ec264b69240959fb685c75a585bccf63325cc2596

# Install php-ext for modstart
RUN . /opt/easysoft/scripts/libcomponent.sh && component_unpack "php-ext-modstart" "7.0.33" \
    -c 645f2945f348467df62d29335897beb4fa752a4283398105099def5cf02457ae

# Install render-template
RUN . /opt/easysoft/scripts/libcomponent.sh && component_unpack "render-template" "1.01" \
    -c 8ebb99a7745352b76dc4cf51815dcfbbc3c9ddb9bda1838b8bca5fbf910bf035

# Install mysql-client
RUN . /opt/easysoft/scripts/libcomponent.sh && component_unpack "mysql-client" "5.5" \
    -c db092fc9b2df26d4638e5f4ce4e95c1c4e467643bf659e7f1f2f7a7b19dd5245
