APP_ENV=product
APP_DEBUG={{DEBUG}}
APP_KEY=4LmYVxyQ0twIjPtNguwEgxDN68oEhBYH

DB_HOST={{MYSQL_HOST}}
DB_DATABASE={{MYSQL_DB}}
DB_USERNAME={{MYSQL_USER}}
DB_PASSWORD={{MYSQL_PASSWORD}}
DB_PREFIX=

CACHE_DRIVER=file
SESSION_DRIVER=file

ADMIN_PATH=/admin/