#!/bin/bash

#==========#
#   php    #
#==========#
export PHP_SESSION_TYPE=${PHP_SESSION_TYPE:-files}
export PHP_SESSION_PATH=${PHP_SESSION_PATH:-/data/php/session}
export PHP_ERROR_LOG=${PHP_ERROR_LOG:-/data/php/log/error.log}

# Nginx
export APP_DOMAIN=${APP_DOMAIN:-_}

#===========#
#   MySQL   #
#===========#
export DB_HOST=${MYSQL_HOST:-127.0.0.1}
export DB_PORT=${MYSQL_PORT:-3306}
export DB_DATABASE=${MYSQL_DB:-modstart}
export DB_USERNAME=${MYSQL_USER:-root}
export DB_PASSWORD=${MYSQL_PASSWORD:-pass4you}

# ======================#
# Persistence directory #
#=======================#
export PHP_PERSISTENCE_LIST=(
"/data/php/log"
"/data/php/session"
"/data/modstartcms")

#==========================================#
# Persistence directory and make soft link #
#==========================================#
export PERSISTENCE_LINK_LIST=(
"/data/modstartcms/public/data"
"/data/modstartcms/storage")

# module list for rsync
export MODULE_LIST=(
"AdminManager"
"Article"
"Banner"
"Cms"
"Member"
"ModuleStore"
"Nav"
"Partner"
"Site"
"Vendor")