#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global/Apache/PHP environment variables
. /etc/s6/s6-init/envs

#==================================#
# Prepare persistence directories. #
#==================================#
info "Prepare persistence directories."
for pdir in "${PHP_PERSISTENCE_LIST[@]}"
do
    # Ensure a directory exists and,is owned by the given user
    ensure_dir_exists "$pdir" "www-data"
done

# Make soft link for persistent directory
if [ ! -f /data/.init_cfg ];then
    for ldir in "${PERSISTENCE_LINK_LIST[@]}"
    do
        ensure_dir_exists "$(dirname $ldir)" "www-data"
        ensure_dir_exists "${ldir/data/apps}" "www-data" "777"
        mv "${ldir/data/apps}" "$(dirname $ldir)"
        make_soft_link "$ldir" "${ldir/data/apps}" "www-data"
    done

    # process module directory
    ensure_dir_exists "/data/modstartcms/module" "www-data"
    for m in "${MODULE_LIST[@]}"
    do
        info "Rsync /apps/modstartcms/module/$m to /data/modstartcms/module ..."
        rsync -a --delete /apps/modstartcms/module/"$m" /data/modstartcms/module
    done
    make_soft_link "/data/modstartcms/module" "/apps/modstartcms/module" "www-data"

    # process other directory
    make_soft_link "/apps/modstartcms/vendor" "/data/modstartcms/vendor" "www-data"
    make_soft_link "/apps/modstartcms/bootstrap" "/data/modstartcms/bootstrap" "www-data"
    make_soft_link "/apps/modstartcms/app" "/data/modstartcms/app" "www-data"

    # process .env file
    [ ! -e /data/modstartcms/.env ] \
    && touch /data/modstartcms/.env \
    && owned_by "/data/modstartcms/.env" "www-data"

    make_soft_link "/data/modstartcms/.env" "/apps/modstartcms/.env" "www-data"
    
    touch /data/.init_cfg
else
    for ldir in "${PERSISTENCE_LINK_LIST[@]}"
    do
        make_soft_link "$ldir" "${ldir/data/apps}" "www-data"
    done

    for m in "${MODULE_LIST[@]}"
    do
        info "Rsync /apps/modstartcms/module/$m to /data/modstartcms/module ..."
        rsync -a --delete /apps/modstartcms/module/"$m" /data/modstartcms/module
    done

    # make .env file soft link
    make_soft_link "/data/modstartcms/.env" "/apps/modstartcms/.env" "www-data"

fi

#=====================#
#   Prepare PHP       #
#=====================#
PHP_INI="/usr/local/etc/php/php.ini"

info "Render php.ini with environment variables."
/usr/bin/render-template ${PHP_INI}.tpl > ${PHP_INI}

#================================#
#   Prepare ModStart env file    #
#================================#
MODSTART_ENV="/apps/modstartcms/env"
info "Render ModStart config with envionment variables."
/usr/bin/render-template ${MODSTART_ENV}.tpl > $MODSTART_ENV

#======================#
# Check MySQL service  #
#======================#
# Check and waiting mysql to be ready
wait_for_mysql || exit 1

# Initialize database
mysql_init_db "$MYSQL_DB"

# Clear install.php
[ -e /apps/modstartcms/storage/install.lock ] && rm -f /apps/modstartcms/public/install.php